### ISSUE TITLE
White screen while running Risk game - TotalRisk-1.2.98

### ISSUE THREAD

**Issue by drdalan** [ToWelie89/TotalRisk#2]
Hello,

When running the "npm run electron:dev" command, I get a white screen.
see below for more details about the npm install process.

npm install
[npm install output.txt](https://github.com/ToWelie89/TotalRisk/files/3378868/npm.install.output.txt)

There were a few dependencies I had to install manually, and "fsevents@1.2.9" was unable to install due to an OS mismatch.

Running "npm run electron:dev"

Here is the output and screen shot.

![Electron](https://user-images.githubusercontent.com/13296067/60993388-391de280-a303-11e9-9da1-2180d215a25b.png)
[electron console output.txt](https://github.com/ToWelie89/TotalRisk/files/3378872/electron.console.output.txt)

Feels like I am missing something simple.

Dalan.

**Comment by ToWelie89** [comment]
Hello Dalan!

I think these are actually two different problems. First problem is the blank screen, the second problem is the spamming of errors in the terminal. These two things are not realated though (I'm 95% sure)

First, pull the latest changes (I made some small changes in 1.2.99). Then run "npm install" (this will install a newer electron version)

**Problem 1**
It looks like you simply have forgotten to build the project. The project doesn't find the necessary built files (app.bundle.js and default.css) which is why these are red in the network tab. To build simply run:
```
grunt
```
If this doesn't work that means you don't have grunt installed globally. In that case first run:
```
npm install --global grunt grunt-cli
```
After you have built the app you can run it normally ("npm start" in one terminal and then "npm run electron:dev" in another)

**Problem 2**
This one is a bit trickier. I can't reproduce the problem myself, but this seems to be a problem related to chrome web tools within an electron app.

First of all, please run the following command in chrome web tools (the one inside the electron app)
```
navigator.appVersion
```
and let me know what it says. It will help me identify your chromium version. This is what I have:

![image](https://user-images.githubusercontent.com/5618925/61001844-b3308480-a360-11e9-9f66-bbb5eae6a32d.png)

You can try and see if you can still run the game (now that you have built it). Even if the terminal is being spammed with error messages, I suspect the game might still work as normal. If not you can try running without web tools altogether by running:
```
npm run electron:dev-no-tools
```
This will do the exact same thing as "npm run electron:dev" but without opening chrome dev tools. See if that helps.

**Comment by ToWelie89** [comment]
**UPDATE**: So I just found out how you may stop the flooding of error messages of "Could not instantiate: ProductRegistryImpl.Registry....".

As I suspected it has something to do with chrome web tools within the electron application. But it doesn't seem to be a blocker. I managed to reproduce it but I could still run the game and everything.

These errors seem to have to do with the "network" tab in web tools. If you open the game and it starts of in network tab, the errors come. So instead switch to for instance "console" tab, then close the game, and start it again. It should now remain in console tab and the error messages should not come.

This is obviously an annoying problem, but like I said, it doesn't seem to block anything in the game, and it is up to electron to fix this on their side.

**Comment by ToWelie89** [comment]
Please let me know if it worked out for you :)

**Comment by drdalan** [comment]
A coworker and I were trying all yesterday and this morning. We could not get npm start to show anything other than a white page.
I installed Ubuntu 19.04, install grunt globally, npm install npm start. Boom everything works. For the last few hours the office has been playing.

Sorry for the run around on my bad server.

One thing, your dice algorithm favors the AI it's brutal, I want to go to Vegas and have the AI roll craps for me.

Thank you.
